---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.01.2020 1:15
---
DestructableState={}
function InitDestructablesActions()
	AnyDeathDestructEnum = CreateTrigger()
	--AnyDeathDestruct = CreateTrigger()
	EnumDestructablesInRect(bj_mapInitialPlayableArea,nil, function()
		TriggerRegisterDeathEvent(AnyDeathDestructEnum, GetEnumDestructable())
	end)
	TriggerAddAction(AnyDeathDestructEnum, function()
		local d=GetTriggerDestructable()
		--print("умер"..GetDestructableName(d))
		local SpawnTime=GetRandomInt(30,60)
		if DestructableState[GetHandleId(d)]==nil then
			--print("убит с руки")
			local data={}
			local KillerID=99
			for i = 0, 3 do
				local id=GetPlayerId(Player(i))
				data[i+1]=R2I(DistanceBetweenXY(GetDestructableX(d),GetDestructableY(d),GetUnitX(HEROSimple[id+1]),GetUnitY(HEROSimple[id+1])))
			end
			local min=math.min (data[1],data[2],data[3],data[4])
			for i = 1, 4 do if data[i]==min then KillerID=i-1	end	end
			FlyTextTagLumberBounty(HEROSimple[KillerID+1],"+"..1,Player(KillerID))
			AdjustPlayerStateBJ(1, Player(KillerID), PLAYER_STATE_RESOURCE_LUMBER )
		end
		DestructableState[GetHandleId(d)]=nil
		TimerStart(CreateTimer(), SpawnTime, false, function()
			DestructableRestoreLife(d, GetDestructableMaxLife(d), true)
			PauseTimer(GetExpiredTimer())
			DestroyTimer(GetExpiredTimer())
		end)
	end)
end