---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.01.2020 22:05
---
do
	local InitGlobalsOrigin = InitGlobals -- записываем InitGlobals в переменную
	function InitGlobals()
		-- заменяем оригинальную InitGlobals своей
		InitGlobalsOrigin() -- вызываем оригинальную InitGlobals из переменной
		--добавляем в список функции для инициализации
		InitSpellTrigger()
		InitMouseMoveTrigger()
		--print("globalinit")
		InitGameCore()
		InitDamage()
		InitTimers()
	end

end
HERO    = {} -- таблица героев
HERO_ID = FourCC('H000') -- ид единственного героя

ARMOR_TIME_COOLDOWN = 10 -- время снятия заряда пассивки

function InitGameCore()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		if GetPlayerController(player) == MAP_CONTROL_USER and GetPlayerSlotState(player) == PLAYER_SLOT_STATE_PLAYING then
			--FIXME сделать нормальное появление героя
			local hero = CreateUnit(player, HERO_ID, 0, 0, 0)
			
			-- пассивка
			UnitAddAbility(hero, FourCC('Asud'))
			AddUnitToStock(hero, FourCC('n000'), 0, 0)
			HERO[GetHandleId(hero)] = {
				unit         = hero, -- ссылка на юнита
				-- пассивка
				armorDamage  = 0, -- полученный урон
				armorElapsed = 0, -- время снятия заряда
				armorCharge  = 0 -- количество зарядов
			}
		end
	end
end

