---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 23.01.2020 20:04
Quest={
	isend=false,
	questendunit=nil,
	hero=nil,
	isactive=false
}
function AddQuest(questnumber,compas,hero,qx,qy,questendunit)
	local x,y=GetUnitX(hero),GetUnitY(hero)
	local QuestPointer=AddSpecialEffect("war3mapImported/AneuCaster.mdl",x,y)
	local data=Quest[questnumber]
	data.hero=hero
	data.questendunit=questendunit
	data.isactive=true
	BlzSetSpecialEffectPitch(QuestPointer,math.rad(-90))--/bj_DEGTORAD
	if compas then
		TimerStart(CreateTimer(), 0.03, true, function()
			local z=GetUnitZ(hero)
			local xc,yc=GetUnitX(hero),GetUnitY(hero)
			local Angle=AngleBetweenXY(xc,yc,qx,qy)
			BlzSetSpecialEffectPosition(QuestPointer,MoveX(xc,130,Angle/bj_DEGTORAD),MoveY(yc,130,Angle/bj_DEGTORAD),z+10)
			BlzSetSpecialEffectYaw(QuestPointer,Angle)
		end)
	end

	if data.isend then
		DestroyEffect(QuestPointer)
		print("квесты выполнен, играем музыку, даём награду")
	end
end