---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 23.01.2020 20:04

function AddQuest(questnumber,compas,hero,qx,qy,questendunit)
	local x,y=GetUnitX(hero),GetUnitY(hero)
	local model="war3mapImported/AneuCaster.mdl"
	local player=GetOwningPlayer(hero)
	--FIXME GetLocalPlayer
	if GetLocalPlayer()~=player then	model="" end
	local QuestPointer=AddSpecialEffect(model,x,y)
	local data=Quest[questnumber]
	data.hero=hero
	data.questendunit=questendunit
	data.isactive=true
	BlzSetSpecialEffectPitch(QuestPointer,math.rad(-90))--/bj_DEGTORAD

	if compas==true then
		TimerStart(CreateTimer(), 0.03, true, function()
			local z=GetUnitZ(hero)
			local xc,yc=GetUnitX(hero),GetUnitY(hero)
			if questendunit~=nil then
				qx,qy=GetUnitX(questendunit),GetUnitY(questendunit)
			end
			local Angle=AngleBetweenXY(xc,yc,qx,qy)
			BlzSetSpecialEffectPosition(QuestPointer,MoveX(xc,130,Angle/bj_DEGTORAD),MoveY(yc,130,Angle/bj_DEGTORAD),z+10)
			BlzSetSpecialEffectYaw(QuestPointer,Angle)

			if data.isend==true then
				if GetLocalPlayer()==player then
					StartSound(bj_questCompletedSound)
					DestroyTimer(GetExpiredTimer())
					DestroyEffect(QuestPointer)
					print("квест "..questnumber.." выполнен, даём награду")
				end
			end
		end)
		TimerStart(CreateTimer(), 10, true, function()
			PingMinimapForPlayer(player,qx,qy,3)
			if data.isend==true then
				DestroyTimer(GetExpiredTimer())
				--print("Выключаем мигалку")
			end
		end)
	end
end
--BlzSetSpecialEffectMatrixScale()

function FindUnitOfType(id)
	local unit=nil
	local e--временный юнит
	local k=0
	--print("ищем")
	GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
	while true do
		e = FirstOfGroup(perebor)

		if e == nil then break end
		if UnitAlive(e) and GetUnitTypeId(e)==id then
			k=k+1
			--print("найден")
			--UnitDamageTarget( u, e, damage, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS )
			unit=e
		end
		GroupRemoveUnit(perebor,e)
	end
	if k>1 then
		print("Ошибка получено "..k.." юнитов")
	end
	if unit==nil then
		print("Не найдено живых юнитов данного типа")

	end
	return unit
end
