---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 17.01.2020 22:52
---
--FIXME
SECOND=0
group=CreateGroup()
function InitTimers()
	TimerStart(CreateTimer(), 1, true, function()
		SECOND = SECOND + 1
	end)
	for index = BlzGroupGetSize(group) - 1, 0, -1 do
		local target = BlzGroupUnitAt(group, index)
		local data = HandleData[GetHandleId(target)]
		local duration=10
		if (data==nil) then data = {} HandleData[GetHandleId(target)] = data end

		if data.chargeMinusTime < SECOND then
			print("отнимаем заряд")
			data.chargeMinusTime = SECOND + duration
			data.stack=data.stack-1
			AddUnitToStock(target,FourCC('n000'),data.stack,data.stack)
		end

	end
end