---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 17.01.2020 22:52
---
--FIXME
--TODO
SECOND = 0
function InitTimers()
	TimerStart(CreateTimer(), 1, true, function()
		SECOND         = SECOND + 1
		-- пассивка
		local duration = 10
		for _, data in pairs(HERO) do
			local hero = data.unit
			if data.armorElapsed < SECOND and data.armorCharge > 0 then
				print 'отнимаем заряд'
				data.armorElapsed = SECOND + duration
				data.armorCharge  = data.armorCharge - 1
				AddUnitToStock(hero, FourCC('n000'), data.armorCharge, data.armorCharge)
			end
		end
	end)
end