---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.01.2020 23:44
---
function InitTalantItemUse()
	gg_trg_TalantItemUse = CreateTrigger()
	TriggerRegisterAnyUnitEventBJ(gg_trg_TalantItemUse, EVENT_PLAYER_UNIT_PICKUP_ITEM)
	TriggerAddAction(gg_trg_TalantItemUse, function()
		local item=GetManipulatedItem()
		local hero=GetTriggerUnit()
		local data=HERO[GetHandleId(hero)]

		if GetItemTypeId(item)==FourCC('I000') then --дополнительные звенья
			local dataT=data.TalantW
			dataT.AddChain=true
			print("изучен прототип таланта "..GetUnitName(hero))
		end
	end)
end